/* Rel.AI Companion — conversation productivity and session health */
(() => {
  'use strict';
  if (globalThis.__RELAI_FEATURES__) return;
  globalThis.__RELAI_FEATURES__ = true;

  const TURN = '[data-testid^="conversation-turn-"]';
  const USER = `${TURN}[data-turn="user"]`;
  const DEFAULTS = {
    commandPaletteEnabled:true,navigatorPreviewsEnabled:true,bookmarksEnabled:true,
    conversationSearchEnabled:true,outlineEnabled:true,focusModeEnabled:false,
    sessionHealthWarnings:true,sessionAutoManage:false,sessionAutoMode:'balanced'
  };
  const KEYS = Object.keys(DEFAULTS);
  const THRESHOLD = { conservative:86, balanced:76, aggressive:62 };
  let prefs = {...DEFAULTS}, baseline = null, lastHealth = null, palette = null, matches = [];
  let longTasks = [], healthTimer = null, navObserver = null, routeKey = convoKey(), notice = null;

  const turns = () => [...document.querySelectorAll(TURN)];
  const users = () => [...document.querySelectorAll(USER)];
  const textOf = el => ((el?.querySelector('[data-message-author-role]') || el)?.innerText || '').replace(/\s+/g,' ').trim();
  const roleOf = el => el?.getAttribute('data-turn') || el?.querySelector('[data-message-author-role]')?.getAttribute('data-message-author-role') || 'message';
  const turnKey = (el,i=0) => el?.getAttribute('data-turn-id') || el?.getAttribute('data-testid') || `${roleOf(el)}:${i}:${textOf(el).slice(0,42)}`;
  const short = (s,n=90) => { s=String(s||'').trim(); return s.length>n ? s.slice(0,n-1)+'…' : (s||'Empty message'); };
  function convoKey(){ const m=location.pathname.match(/(?:^|\/)c\/([^/?#]+)/); return m?`c:${m[1]}`:`path:${location.pathname}`; }
  function scrollTo(el){ (el?.closest('[data-turn-id-container]')||el)?.scrollIntoView({behavior:'smooth',block:'start'}); }

  function scrollContainer(el){ let n=el?.parentElement; while(n&&n!==document.body){ const s=getComputedStyle(n); if(/auto|scroll/.test(s.overflowY)&&n.scrollHeight>n.clientHeight+20) return n; n=n.parentElement; } return document.scrollingElement||document.documentElement; }
  function currentUser(){ const u=users(); if(!u.length) return -1; const sc=scrollContainer(u[0]); const top=(sc===document.documentElement||sc===document.scrollingElement)?0:sc.getBoundingClientRect().top; let idx=0; u.forEach((el,i)=>{ if(el.getBoundingClientRect().top-top<=130) idx=i; }); return idx; }

  function lightPage(){ for(const el of [document.querySelector('main'),document.body,document.documentElement]){ if(!el) continue; const m=getComputedStyle(el).backgroundColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); if(m) return .2126*m[1]+.7152*m[2]+.0722*m[3]>150; } return false; }
  const theme = el => el?.classList.toggle('relai-light',lightPage());

  async function loadPrefs(){ const d=await chrome.storage.local.get(KEYS); prefs={...DEFAULTS}; for(const k of KEYS) if(k in d&&typeof d[k]===typeof DEFAULTS[k]) prefs[k]=d[k]; if(!THRESHOLD[prefs.sessionAutoMode]) prefs.sessionAutoMode='balanced'; document.documentElement.classList.toggle('relai-focus-mode',!!prefs.focusModeEnabled); }
  async function bookmarks(){ const d=await chrome.storage.local.get('relaiBookmarks'); const all=d.relaiBookmarks||{}; return Array.isArray(all[convoKey()])?all[convoKey()]:[]; }
  async function saveBookmarks(list){ const d=await chrome.storage.local.get('relaiBookmarks'); const all=d.relaiBookmarks||{}; all[convoKey()]=list.slice(0,250); await chrome.storage.local.set({relaiBookmarks:all}); refreshNav(); }
  async function toggleBookmark(){ const u=users(), i=currentUser(); if(i<0) return {success:false}; const key=turnKey(u[i],i), list=await bookmarks(), x=list.findIndex(b=>b.key===key); if(x>=0){ list.splice(x,1); await saveBookmarks(list); return {success:true,bookmarked:false,count:list.length}; } list.push({key,index:i,label:short(textOf(u[i]),110),createdAt:Date.now()}); await saveBookmarks(list); return {success:true,bookmarked:true,count:list.length}; }

  function search(q){ q=String(q||'').trim().toLowerCase(); if(q.length<2){ matches=[]; refreshNav(); return []; } const out=[]; turns().forEach((el,i)=>{ const txt=textOf(el), p=txt.toLowerCase().indexOf(q); if(p<0) return; out.push({key:turnKey(el,i),index:i,role:roleOf(el),label:short(txt.slice(Math.max(0,p-28),p+q.length+72),112),el}); }); matches=out.slice(0,80); refreshNav(); return out.slice(0,30); }
  function outline(){ return users().map((el,i)=>({key:turnKey(el,i),index:i,label:short(textOf(el),105),el})); }

  function observeLongTasks(){ if(typeof PerformanceObserver==='undefined'||!PerformanceObserver.supportedEntryTypes?.includes('longtask')) return; try{ new PerformanceObserver(list=>{ const now=performance.now(); list.getEntries().forEach(e=>longTasks.push({t:now,d:e.duration})); longTasks=longTasks.filter(x=>x.t>now-60000); }).observe({type:'longtask',buffered:true}); }catch{} }
  function metrics(){ const now=performance.now(); longTasks=longTasks.filter(x=>x.t>now-60000); const m=performance.memory; return {heapBytes:m?.usedJSHeapSize||null,domNodes:document.getElementsByTagName('*').length,turns:turns().length,renderedTurns:document.querySelectorAll(`${TURN} [data-message-author-role]`).length,longTaskCount60s:longTasks.length,longTaskMs60s:Math.round(longTasks.reduce((s,x)=>s+x.d,0)),tabAgeMinutes:Math.round(now/60000)}; }
  function health(){ const m=metrics(); if(!baseline) baseline={...m}; let s=0, mb=(m.heapBytes||0)/1048576; s+=mb>=700?45:mb>=500?34:mb>=350?22:mb>=250?10:0; s+=m.domNodes>=30000?30:m.domNodes>=20000?23:m.domNodes>=12000?15:m.domNodes>=7000?7:0; s+=m.turns>=300?20:m.turns>=180?14:m.turns>=100?8:m.turns>=50?4:0; s+=m.longTaskCount60s>=20?15:m.longTaskCount60s>=10?10:m.longTaskCount60s>=5?5:0; s=Math.min(100,s); const label=s>=76?'Critical':s>=55?'Heavy':s>=30?'Moderate':'Good'; return lastHealth={score:s,label,metrics:m,baseline,delta:{heapBytes:m.heapBytes!=null&&baseline.heapBytes!=null?m.heapBytes-baseline.heapBytes:null,domNodes:m.domNodes-baseline.domNodes}}; }
  function hasDraft(){ const t=document.querySelector('textarea'); if(t?.value.trim()) return true; const e=document.querySelector('[contenteditable="true"]'); return !!e?.innerText?.trim(); }
  function streaming(){ return !!document.querySelector('[data-testid="stop-button"],button[aria-label*="Stop" i],.result-streaming'); }
  function reset(auto=false){ try{ sessionStorage.setItem(auto?'relaiAutoResetAt':'relaiManualResetAt',String(Date.now())); }catch{} location.reload(); }
  function removeNotice(){ notice?.remove(); notice=null; }
  function warn(h,auto=false){ if(notice||hasDraft()||streaming()) return; const n=document.createElement('div'); n.className='relai-health-notice'; theme(n); n.innerHTML=`<strong>Session health: ${h.label}</strong><span>${auto?'This tab is under heavy load. Memory Reset will reload it in 8 seconds.':'This tab is under heavy load. You can reload the current conversation to release accumulated resources.'}</span><div class="relai-health-actions"><button type="button">Reset now</button><button type="button">${auto?'Cancel':'Ignore'}</button></div>`; const [go,no]=n.querySelectorAll('button'); go.onclick=()=>reset(auto); no.onclick=()=>{ try{sessionStorage.setItem('relaiHealthIgnoreUntil',String(Date.now()+600000));}catch{} removeNotice(); }; document.body.appendChild(n); notice=n; if(auto) setTimeout(()=>{ if(notice===n) reset(true); },8000); }
  function tickHealth(){ const h=health(); let ignore=0,last=0; try{ignore=Number(sessionStorage.getItem('relaiHealthIgnoreUntil')||0);last=Number(sessionStorage.getItem('relaiAutoResetAt')||0);}catch{} if(Date.now()<ignore) return; const auto=prefs.sessionAutoManage&&h.score>=(THRESHOLD[prefs.sessionAutoMode]||76)&&Date.now()-last>900000; if(auto) warn(h,true); else if(prefs.sessionHealthWarnings&&h.score>=76) warn(h,false); else if(h.score<55) removeNotice(); }

  async function refreshNav(){ const nav=document.getElementById('relai-nav'); if(!nav) return; if(!nav.dataset.relaiEnhanced){ nav.dataset.relaiEnhanced='1'; const markers=document.createElement('div'); markers.className='relai-nav-markers'; nav.appendChild(markers); const preview=document.createElement('div'); preview.className='relai-nav-preview'; preview.hidden=true; nav.appendChild(preview); nav.addEventListener('pointermove',e=>{ if(!prefs.navigatorPreviewsEnabled) return; const u=users(), track=nav.querySelector('.relai-nav-track'); if(!u.length||!track) return; const r=track.getBoundingClientRect(), ratio=Math.max(0,Math.min(1,(e.clientY-r.top)/Math.max(1,r.height))), i=Math.round(ratio*(u.length-1)); preview.textContent=`${i+1} / ${u.length} · ${short(textOf(u[i]),76)}`; preview.style.top=`${Math.max(8,Math.min(92,ratio*100))}%`; preview.hidden=false; }); nav.addEventListener('pointerleave',()=>preview.hidden=true); }
    const box=nav.querySelector('.relai-nav-markers'); if(!box) return; box.textContent=''; const preview=nav.querySelector('.relai-nav-preview'); if(!prefs.navigatorPreviewsEnabled){ if(preview) preview.hidden=true; return; } const u=users(); if(u.length<2) return; const b=new Set((await bookmarks()).map(x=>x.key)), s=new Set(matches.map(x=>x.key)); u.forEach((el,i)=>{ const key=turnKey(el,i); if(!b.has(key)&&!s.has(key)) return; const m=document.createElement('button'); m.type='button'; m.className=`relai-nav-marker${b.has(key)?' relai-nav-marker-bookmark':''}${s.has(key)?' relai-nav-marker-search':''}`; m.style.top=`${i/Math.max(1,u.length-1)*100}%`; m.onclick=e=>{e.stopPropagation();scrollTo(el)}; box.appendChild(m); }); }
  function watchNav(){ navObserver=new MutationObserver(()=>{ if(document.getElementById('relai-nav')) refreshNav(); }); navObserver.observe(document.documentElement,{childList:true,subtree:true}); refreshNav(); }

  function compat(){ const ts=turns(), us=users(); const spec=typeof HTMLScriptElement.supports==='function'&&HTMLScriptElement.supports('speculationrules'); const lt=PerformanceObserver?.supportedEntryTypes?.includes?.('longtask'); return {turns:{status:ts.length?'ok':'warn',detail:ts.length?`${ts.length} turns detected`:'No turns detected yet'},userTurns:{status:us.length?'ok':'warn',detail:us.length?`${us.length} user turns detected`:'No user turns detected yet'},composer:{status:document.querySelector('textarea,[contenteditable="true"]')?'ok':'warn',detail:'Composer selector check'},navigator:{status:document.getElementById('relai-nav')?'ok':'info',detail:document.getElementById('relai-nav')?'Conversation rail mounted':'Rail disabled or conversation too short'},memory:{status:performance.memory?'ok':'info',detail:performance.memory?'JS heap metrics available':'JS heap metrics unavailable'},longTasks:{status:lt?'ok':'info',detail:lt?'Long-task metrics available':'Long-task metrics unavailable'},quickOpen:{status:spec?'ok':'info',detail:spec?'Speculation Rules supported; Chromium still decides whether to prerender':'Speculation Rules unsupported'},sessionCheck:{status:'info',detail:'Session Check is experimental; login extension is not asserted'}}; }

  function createPalette(){ if(palette) return palette; const root=document.createElement('div'); root.id='relai-command-palette'; root.className='relai-palette-backdrop'; root.hidden=true; root.innerHTML='<section class="relai-palette" role="dialog" aria-modal="true" aria-label="Rel.AI command palette"><div class="relai-palette-input-wrap"><input class="relai-palette-input" type="search" autocomplete="off" placeholder="Search messages or actions…"><kbd>Esc</kbd></div><div class="relai-palette-meta"></div><div class="relai-palette-results"></div><div class="relai-palette-footer"><span>↑↓ Move</span><span>Enter Open</span><span>Ctrl Shift K Toggle</span></div></section>'; document.body.appendChild(root); root.onclick=e=>{if(e.target===root) closePalette()}; root.querySelector('input').oninput=e=>renderPalette(e.target.value); root.querySelector('input').onkeydown=e=>{ if(e.key==='Escape'){e.preventDefault();closePalette()} }; palette=root; return root; }
  async function renderPalette(q=''){ const root=createPalette(), list=root.querySelector('.relai-palette-results'), meta=root.querySelector('.relai-palette-meta'); list.textContent=''; const commands=[['Bookmark current prompt','Save or remove the nearest prompt bookmark',async()=>{await toggleBookmark();closePalette()}],['Show bookmarks','Browse saved prompt positions',()=>showBookmarks()],['Conversation outline','Browse your prompts',()=>showOutline()],['Focus Mode',document.documentElement.classList.contains('relai-focus-mode')?'Exit Focus Mode':'Hide surrounding ChatGPT chrome',()=>{const v=!document.documentElement.classList.contains('relai-focus-mode');document.documentElement.classList.toggle('relai-focus-mode',v);chrome.storage.local.set({focusModeEnabled:v});renderPalette('')}],['Session health',lastHealth?`${lastHealth.label} · ${lastHealth.score}/100`:'View local session signals',()=>showHealth()],['Memory Reset now','Reload the current conversation tab',()=>reset(false)],['Compatibility diagnostics','Check ChatGPT selectors and browser capabilities',()=>showCompat()]]; const rows=[]; if(q.trim().length>=2&&prefs.conversationSearchEnabled) rows.push(...search(q).map(x=>[x.label,`${x.role} message`,()=>{scrollTo(x.el);closePalette()}])); commands.filter(x=>!q||(`${x[0]} ${x[1]}`).toLowerCase().includes(q.toLowerCase())).forEach(x=>rows.push(x)); meta.textContent=q.trim().length>=2?`${rows.length} results`:'Commands and local conversation search'; rows.slice(0,40).forEach(([a,b,fn])=>{const el=document.createElement('button');el.type='button';el.className='relai-palette-row';el.innerHTML='<strong></strong><small></small>';el.querySelector('strong').textContent=a;el.querySelector('small').textContent=b;el.onclick=fn;list.appendChild(el)}); if(!list.childElementCount) list.innerHTML='<div class="relai-palette-empty">No results</div>'; }
  function openPalette(){ if(!prefs.commandPaletteEnabled) return false; const r=createPalette(); theme(r); r.hidden=false; const input=r.querySelector('input'); input.value=''; renderPalette(''); setTimeout(()=>input.focus(),0); return true; }
  function closePalette(){ if(palette) palette.hidden=true; matches=[]; refreshNav(); }
  async function showBookmarks(){ const list=await bookmarks(), u=users(), root=createPalette(), box=root.querySelector('.relai-palette-results'); root.querySelector('.relai-palette-meta').textContent=`${list.length} bookmarks`; box.textContent=''; list.forEach(b=>{const el=u.find((n,i)=>turnKey(n,i)===b.key)||u[b.index]; if(!el) return; const row=document.createElement('button');row.className='relai-palette-row';row.innerHTML='<strong></strong><small></small>';row.querySelector('strong').textContent=b.label;row.querySelector('small').textContent=`Prompt ${b.index+1}`;row.onclick=()=>{scrollTo(el);closePalette()};box.appendChild(row)}); }
  function showOutline(){ const root=createPalette(),box=root.querySelector('.relai-palette-results'),out=outline(); root.querySelector('.relai-palette-meta').textContent=`${out.length} prompts`; box.textContent=''; out.forEach(x=>{const row=document.createElement('button');row.className='relai-palette-row';row.innerHTML='<strong></strong><small></small>';row.querySelector('strong').textContent=x.label;row.querySelector('small').textContent=`Prompt ${x.index+1}`;row.onclick=()=>{scrollTo(x.el);closePalette()};box.appendChild(row)}); }
  function showHealth(){ const h=health(),root=createPalette(),box=root.querySelector('.relai-palette-results'); root.querySelector('.relai-palette-meta').textContent='Local measurements; score is a heuristic'; box.innerHTML=`<div class="relai-palette-row"><strong>${h.label} · ${h.score}/100</strong><small>Heap ${h.metrics.heapBytes?Math.round(h.metrics.heapBytes/1048576)+' MB':'unavailable'} · DOM ${h.metrics.domNodes.toLocaleString()} · ${h.metrics.turns} turns · ${h.metrics.longTaskCount60s} long tasks/60s</small></div>`; }
  function showCompat(){ const root=createPalette(),box=root.querySelector('.relai-palette-results'),r=compat(); root.querySelector('.relai-palette-meta').textContent='Compatibility checks'; box.textContent=''; Object.entries(r).forEach(([k,v])=>{const el=document.createElement('div');el.className='relai-palette-row';el.innerHTML='<strong></strong><small></small>';el.querySelector('strong').textContent=`${k}: ${v.status.toUpperCase()}`;el.querySelector('small').textContent=v.detail;box.appendChild(el)}); }

  chrome.runtime.onMessage.addListener((msg,_s,reply)=>{ if(!msg?.action?.startsWith?.('RELAI_')) return; if(msg.action==='RELAI_FEATURES_STATUS'){ Promise.all([bookmarks(),loadPrefs()]).then(([b])=>reply({success:true,health:health(),bookmarks:b.length,focusMode:document.documentElement.classList.contains('relai-focus-mode'),prefs:{...prefs},compatibility:compat()})); return true; } if(msg.action==='RELAI_OPEN_PALETTE'){reply({success:openPalette()});return;} if(msg.action==='RELAI_TOGGLE_BOOKMARK'){toggleBookmark().then(reply);return true;} if(msg.action==='RELAI_SET_FOCUS'){document.documentElement.classList.toggle('relai-focus-mode',!!msg.enabled);chrome.storage.local.set({focusModeEnabled:!!msg.enabled});prefs.focusModeEnabled=!!msg.enabled;reply({success:true});return;} if(msg.action==='RELAI_RUN_COMPAT'){reply({success:true,report:compat()});return;} if(msg.action==='RELAI_RESET_NOW'){reply({success:true});setTimeout(()=>reset(false),50);return;} });
  chrome.storage.onChanged.addListener((c,a)=>{ if(a!=='local')return; KEYS.forEach(k=>{if(k in c&&typeof c[k].newValue===typeof DEFAULTS[k])prefs[k]=c[k].newValue}); document.documentElement.classList.toggle('relai-focus-mode',!!prefs.focusModeEnabled); refreshNav(); });
  document.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='k'&&prefs.commandPaletteEnabled){e.preventDefault();palette&&!palette.hidden?closePalette():openPalette();}},true);

  async function init(){ await loadPrefs(); observeLongTasks(); watchNav(); baseline=metrics(); healthTimer=setInterval(()=>{if(!document.hidden)tickHealth()},15000); setInterval(()=>{const k=convoKey();if(k!==routeKey){routeKey=k;baseline=metrics();matches=[];removeNotice();refreshNav()}},1500); }
  init().catch(e=>console.warn('[Rel.AI Companion] Feature layer failed',e?.message||e));
})();
