/* Rel.AI Companion — new minimalist popup controller */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), runtime=chrome.runtime, store=chrome.storage.local;
  const BASE={cleanMemoryEnabled:true,hideNotifications:false,perfResourceHints:true,perfReduceAnim:true,perfOptimizeDom:true,perfFontSwap:true,perfLazyImg:true,perfBlockTrackers:false,perfKeepSession:false,perfDeferScripts:false,navigatorEnabled:true,hudEnabled:false,cleanMemorySmart:false,hideThinking:false,clickToLoadImg:false,prefetchNav:false,blockTrackersNet:false};
  const FEAT={commandPaletteEnabled:true,navigatorPreviewsEnabled:true,bookmarksEnabled:true,conversationSearchEnabled:true,outlineEnabled:true,focusModeEnabled:false,sessionHealthWarnings:true,sessionAutoManage:false,sessionAutoMode:'balanced'};
  const ORIGINS=['*://*.browser-intake-datadoghq.com/*','*://*.datadoghq.com/*','*://*.google-analytics.com/*','*://*.doubleclick.net/*'];
  const PRESETS={
    balanced:{b:{cleanMemoryEnabled:true,cleanMemorySmart:false,hideNotifications:false,perfResourceHints:true,perfReduceAnim:true,perfOptimizeDom:true,perfFontSwap:true,perfLazyImg:true,perfBlockTrackers:false,perfKeepSession:false,perfDeferScripts:false,navigatorEnabled:true,hudEnabled:false,hideThinking:false,clickToLoadImg:false,prefetchNav:false},f:{commandPaletteEnabled:true,navigatorPreviewsEnabled:true,bookmarksEnabled:true,conversationSearchEnabled:true,outlineEnabled:true,focusModeEnabled:false,sessionHealthWarnings:true,sessionAutoManage:false,sessionAutoMode:'balanced'}},
    performance:{b:{cleanMemoryEnabled:true,cleanMemorySmart:true,hideNotifications:true,perfResourceHints:true,perfReduceAnim:true,perfOptimizeDom:true,perfFontSwap:true,perfLazyImg:true,perfBlockTrackers:false,perfKeepSession:false,perfDeferScripts:true,navigatorEnabled:true,hudEnabled:true,hideThinking:false,clickToLoadImg:true,prefetchNav:true},f:{commandPaletteEnabled:true,navigatorPreviewsEnabled:true,bookmarksEnabled:true,conversationSearchEnabled:true,outlineEnabled:true,focusModeEnabled:false,sessionHealthWarnings:true,sessionAutoManage:true,sessionAutoMode:'balanced'}},
    privacy:{b:{cleanMemoryEnabled:true,cleanMemorySmart:false,hideNotifications:true,perfResourceHints:true,perfReduceAnim:true,perfOptimizeDom:true,perfFontSwap:true,perfLazyImg:true,perfBlockTrackers:true,perfKeepSession:false,perfDeferScripts:true,navigatorEnabled:true,hudEnabled:false,hideThinking:true,clickToLoadImg:true,prefetchNav:false},f:{commandPaletteEnabled:true,navigatorPreviewsEnabled:true,bookmarksEnabled:true,conversationSearchEnabled:true,outlineEnabled:true,focusModeEnabled:false,sessionHealthWarnings:true,sessionAutoManage:false,sessionAutoMode:'conservative'}},
    minimal:{b:{cleanMemoryEnabled:false,cleanMemorySmart:false,hideNotifications:false,perfResourceHints:false,perfReduceAnim:false,perfOptimizeDom:false,perfFontSwap:false,perfLazyImg:false,perfBlockTrackers:false,perfKeepSession:false,perfDeferScripts:false,navigatorEnabled:true,hudEnabled:false,hideThinking:false,clickToLoadImg:false,prefetchNav:false},f:{...FEAT,focusModeEnabled:false,sessionHealthWarnings:false,sessionAutoManage:false,sessionAutoMode:'conservative'}}
  };
  let base={...BASE},feat={...FEAT},chatTab=null,toastTimer=null,resetArmed=false;
  const baseControls=[...document.querySelectorAll('[data-pref]')];

  function toast(msg,tone='info',ms=3200){const e=$('toast');e.textContent=msg;e.dataset.tone=tone;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,ms)}
  function paint(el,on){if(!el)return;el.dataset.state=on?'on':'off';el.setAttribute('role','switch');el.setAttribute('aria-checked',String(on));const i=el.querySelector('i');if(i)i.textContent=on?'On':'Off'}
  function paintAll(){baseControls.forEach(el=>paint(el,!!base[el.dataset.pref]));paint($('focusToggle'),feat.focusModeEnabled);paint($('autoManageToggle'),feat.sessionAutoManage);paint($('healthWarningsToggle'),feat.sessionHealthWarnings);paint($('navPreviewToggle'),feat.navigatorPreviewsEnabled);paint($('paletteShortcutToggle'),feat.commandPaletteEnabled);$('autoMode').value=feat.sessionAutoMode;syncPreset()}
  function same(obj,expected){return Object.entries(expected).every(([k,v])=>obj[k]===v)}
  function syncPreset(){const found=Object.entries(PRESETS).find(([,p])=>same(base,p.b)&&same(feat,p.f));$('presetSelect').value=found?found[0]:'custom'}
  async function load(){const d=await store.get([...Object.keys(BASE),...Object.keys(FEAT)]);base={...BASE};feat={...FEAT};Object.keys(BASE).forEach(k=>{if(k in d&&typeof d[k]===typeof BASE[k])base[k]=d[k]});Object.keys(FEAT).forEach(k=>{if(k in d&&typeof d[k]===typeof FEAT[k])feat[k]=d[k]});if(!['conservative','balanced','aggressive'].includes(feat.sessionAutoMode))feat.sessionAutoMode='balanced';paintAll()}
  async function saveBase(changes){const r=await runtime.sendMessage({action:'SET_PREFS',prefs:changes});if(r?.error)throw Error(r.error);Object.assign(base,changes);paintAll()}
  async function saveFeat(changes){Object.assign(feat,changes);await store.set(changes);paintAll()}
  async function findChat(){const active=(await chrome.tabs.query({active:true,currentWindow:true})).find(t=>/^https:\/\/(chatgpt\.com|chat\.openai\.com)\//.test(t.url||''));if(active)return active;return (await chrome.tabs.query({url:['https://chatgpt.com/*','https://chat.openai.com/*']}))[0]||null}
  async function send(action,data={}){chatTab=chatTab||await findChat();if(!chatTab?.id)return null;try{return await chrome.tabs.sendMessage(chatTab.id,{action,...data})}catch{chatTab=null;return null}}

  baseControls.forEach(el=>el.addEventListener('click',async()=>{try{await saveBase({[el.dataset.pref]:!base[el.dataset.pref]})}catch{toast('Could not save setting','error')}}));
  $('focusToggle').onclick=async()=>{const next=!feat.focusModeEnabled,r=await send('RELAI_SET_FOCUS',{enabled:next});if(!r?.success)return toast('Open ChatGPT first','warning');await saveFeat({focusModeEnabled:next});toast(next?'Focus Mode enabled':'Focus Mode disabled','success')};
  $('autoManageToggle').onclick=()=>saveFeat({sessionAutoManage:!feat.sessionAutoManage});
  $('healthWarningsToggle').onclick=()=>saveFeat({sessionHealthWarnings:!feat.sessionHealthWarnings});
  $('navPreviewToggle').onclick=()=>saveFeat({navigatorPreviewsEnabled:!feat.navigatorPreviewsEnabled});
  $('paletteShortcutToggle').onclick=()=>saveFeat({commandPaletteEnabled:!feat.commandPaletteEnabled});
  $('autoMode').onchange=e=>saveFeat({sessionAutoMode:e.target.value});

  async function openPalette(mode){const r=await send('RELAI_OPEN_PALETTE',{mode});if(!r?.success)return toast('Open a ChatGPT conversation first','warning');window.close()}
  $('searchBtn').onclick=()=>openPalette('search');$('outlineBtn').onclick=()=>openPalette('outline');$('paletteBtn').onclick=()=>openPalette('commands');
  $('bookmarkBtn').onclick=async()=>{const r=await send('RELAI_TOGGLE_BOOKMARK');if(!r?.success)return toast('No current prompt to bookmark','warning');$('bookmarkCount').textContent=r.count||0;toast(r.bookmarked?'Prompt bookmarked':'Bookmark removed','success')};

  $('presetSelect').onchange=async e=>{const name=e.target.value,p=PRESETS[name];if(!p)return;try{await saveBase(p.b);await saveFeat(p.f);toast(`${name[0].toUpperCase()+name.slice(1)} preset applied`,'success')}catch{toast('Could not apply preset','error')}};

  async function trackerState(){try{return await runtime.sendMessage({action:'GET_TRACKER_STATE'})}catch{return null}}
  async function paintTracker(){const s=await trackerState();if(!s){$('networkToggle').disabled=true;return}paint($('networkToggle'),!!s.effective);base.blockTrackersNet=!!s.effective;$('networkToggle').disabled=false;const note=$('networkStatus');note.hidden=!s.reason;note.textContent=s.reason==='revoked'?'Site access was revoked. Turn Network Privacy on again to re-authorize.':s.reason==='denied'?'Permission was not granted.':s.reason==='error'?'The browser rules could not be applied.':''}
  $('networkToggle').onclick=async()=>{const want=!base.blockTrackersNet;try{if(want){await store.set({trackerPending:true,trackerPendingAt:Date.now()});const ok=await chrome.permissions.request({origins:ORIGINS});if(!ok){await store.set({trackerPending:false,trackerPendingAt:0});return toast('Permission not granted','warning')}}const r=await runtime.sendMessage({action:'SET_TRACKER_BLOCKING',enabled:want});if(!r?.success)throw Error();await paintTracker();toast(want?'Network Privacy enabled':'Network Privacy disabled','success')}catch{await paintTracker();toast('Could not change Network Privacy','error')}};

  function tone(label){return label==='Critical'?'bad':label==='Heavy'?'warn':'good'}
  function mb(bytes){return typeof bytes==='number'?`${Math.round(bytes/1048576)} MB`:'Unavailable'}
  function delta(v,unit=''){if(typeof v!=='number')return '—';return `${v>0?'+':''}${Math.round(v)}${unit}`}
  function renderStatus(r){if(!r?.success){$('healthCard').hidden=true;return}$('healthCard').hidden=false;$('healthLabel').textContent=r.health.label;$('healthLabel').dataset.tone=tone(r.health.label);$('healthScore').textContent=`${r.health.score}/100`;$('healthMemory').textContent=mb(r.health.metrics.heapBytes);$('healthMemoryDelta').textContent=r.health.delta.heapBytes==null?'—':delta(r.health.delta.heapBytes/1048576,' MB');$('healthDom').textContent=r.health.metrics.domNodes.toLocaleString();$('healthDomDelta').textContent=delta(r.health.delta.domNodes);$('healthTurns').textContent=r.health.metrics.turns;$('bookmarkCount').textContent=r.bookmarks||0;if(r.prefs){Object.assign(feat,r.prefs);paintAll()}renderCompat(r.compatibility)}
  function renderCompat(r){if(!r)return;const map={diagTurns:r.turns,diagNav:r.navigator,diagMemory:r.memory,diagQuick:r.quickOpen,diagSession:r.sessionCheck};Object.entries(map).forEach(([id,x])=>{const e=$(id);if(!x)return;e.textContent=x.status==='ok'?'Working':x.status==='warn'?'Check':'Info';e.dataset.tone=x.status==='ok'?'good':x.status==='warn'?'warn':'muted';e.title=x.detail||''})}
  async function refresh(){chatTab=await findChat();$('connectionText').textContent=chatTab?'Connected to ChatGPT':'ChatGPT not open';$('openChatBtn').textContent=chatTab?'Go to ChatGPT':'Open ChatGPT';if(chatTab)renderStatus(await send('RELAI_FEATURES_STATUS'));else $('healthCard').hidden=true;await paintTracker()}
  $('openChatBtn').onclick=async()=>{if(chatTab){await chrome.tabs.update(chatTab.id,{active:true});if(chatTab.windowId)await chrome.windows.update(chatTab.windowId,{focused:true});return}await chrome.tabs.create({url:'https://chatgpt.com/'})};
  $('compatBtn').onclick=async()=>{const r=await send('RELAI_RUN_COMPAT');if(!r?.success)return toast('Open ChatGPT first','warning');renderCompat(r.report);toast('Compatibility test refreshed','success')};

  async function copyDiag(){const r=await send('RELAI_FEATURES_STATUS'),t=await trackerState();const lines=['Rel.AI Companion diagnostics',`Version: ${runtime.getManifest().version}`,`Browser: ${navigator.userAgent}`,`ChatGPT: ${chatTab?.url||'not found'}`];if(r?.health){lines.push(`Session health: ${r.health.label} (${r.health.score}/100)`,`Heap: ${mb(r.health.metrics.heapBytes)}`,`DOM nodes: ${r.health.metrics.domNodes}`,`Turns: ${r.health.metrics.turns}`,`Bookmarks: ${r.bookmarks||0}`)}if(r?.compatibility)Object.entries(r.compatibility).forEach(([k,v])=>lines.push(`${k}: ${v.status} — ${v.detail}`));if(t)lines.push(`Network Privacy: ${t.effective?'effective':t.reason||'off'}`);try{await navigator.clipboard.writeText(lines.join('\n'));toast('Diagnostics copied','success')}catch{toast('Could not copy diagnostics','error')}}
  $('copyDiagBtn').onclick=copyDiag;

  $('backupBtn').onclick=async()=>{const d=await store.get([...Object.keys(BASE),...Object.keys(FEAT),'relaiBookmarks']),t=await trackerState();const payload={schema:'relai-companion-settings',schemaVersion:2,extensionVersion:runtime.getManifest().version,savedAt:new Date().toISOString(),preferences:{...BASE,...d,blockTrackersNet:!!t?.effective},featurePreferences:Object.fromEntries(Object.keys(FEAT).map(k=>[k,d[k]??FEAT[k]])),bookmarks:d.relaiBookmarks||{}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rel-ai-companion-settings-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Settings and bookmarks backed up','success')};
  $('restoreBtn').onclick=()=>$('fileInput').click();
  $('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.schema!=='relai-companion-settings')throw Error();const b={};Object.keys(BASE).forEach(k=>{if(k!=='blockTrackersNet'&&typeof p.preferences?.[k]===typeof BASE[k])b[k]=p.preferences[k]});const x={};Object.keys(FEAT).forEach(k=>{if(typeof p.featurePreferences?.[k]===typeof FEAT[k])x[k]=p.featurePreferences[k]});await saveBase(b);await saveFeat(x);if(p.bookmarks&&typeof p.bookmarks==='object')await store.set({relaiBookmarks:p.bookmarks});await refresh();toast('Settings restored','success')}catch{toast('Invalid settings backup','error')}finally{e.target.value=''}};
  $('resetBtn').onclick=async()=>{if(!resetArmed){resetArmed=true;$('resetBtn').textContent='Confirm reset';toast('Click Confirm reset to clear settings and bookmarks','warning',4000);setTimeout(()=>{resetArmed=false;$('resetBtn').textContent='Reset'},4200);return}resetArmed=false;$('resetBtn').textContent='Reset';const b={...BASE};delete b.blockTrackersNet;await saveBase(b);await saveFeat({...FEAT});await runtime.sendMessage({action:'SET_TRACKER_BLOCKING',enabled:false}).catch(()=>{});await store.set({relaiBookmarks:{}});await refresh();toast('Rel.AI reset to defaults','success')};
  $('githubBtn').onclick=()=>chrome.tabs.create({url:'https://github.com/Kyne0328/chatgpt-performance-optimizer-web-extension'});$('siteBtn').onclick=()=>chrome.tabs.create({url:'https://kyne.is-a.dev/'});
  chrome.storage.onChanged.addListener((c,a)=>{if(a!=='local')return;Object.keys(BASE).forEach(k=>{if(k in c)base[k]=c[k].newValue});Object.keys(FEAT).forEach(k=>{if(k in c)feat[k]=c[k].newValue});paintAll()});

  (async()=>{await load();await refresh();setInterval(()=>{if(!document.hidden)refresh()},6000)})().catch(()=>toast('Some features could not initialize','warning'));
})();
